-- 리뷰 평균점수
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO 
JOIN (
    SELECT ROUND(SUM(REVIEW_SCORE)/COUNT(REVIEW_ID), 2) AS SCORE, REST_ID AS REST
    FROM REST_REVIEW
    GROUP BY REST_ID
) r ON REST_ID = r.REST
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;